services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: production
            REDIS_URL: "redis://:6E8eLf6ygHHStmSW1s3Z5WrQ14yrHr7KEz2lrLrD77DXLh0gPXWe6d5f1W3ZlMef@redis:6379"
            DATABASE_URL: "postgresql://crypto-platform:crypto-platform@postgres:5432/crypto-platform"
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started

    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: crypto-platform
            POSTGRES_PASSWORD: crypto-platform
            POSTGRES_DB: crypto-platform
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U crypto-platform"]
            interval: 10s
            timeout: 3s
            retries: 5

    redis:
        image: redis:7
        command: ["redis-server", "--requirepass", "6E8eLf6ygHHStmSW1s3Z5WrQ14yrHr7KEz2lrLrD77DXLh0gPXWe6d5f1W3ZlMef"]
        ports:
            - "6379:6379"

volumes:
    postgres_data:
