services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: production
            DATABASE_URL: "postgresql://crypto-platform:crypto-platform@postgres:5432/crypto-platform"
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: crypto-platform
            POSTGRES_PASSWORD: crypto-platform
            POSTGRES_DB: crypto-platform
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U crypto-platform"]
            interval: 10s
            timeout: 3s
            retries: 5

volumes:
    postgres_data:
